# Generated by Django 5.2.4 on 2025-07-04 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('nome', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=64, unique=True)),
                ('documento', models.CharField(max_length=64, unique=True)),
                ('endereco', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
                ('data_cadastro', models.DateField()),
                ('cargo', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=64, unique=True)),
                ('documento', models.CharField(max_length=64, unique=True)),
                ('endereco', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
                ('data_cadastro', models.DateField()),
                ('data_nascimento', models.DateField()),
                ('is_banned', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.IntegerField(verbose_name='Preço')),
                ('prazo', models.DateField()),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
                ('aceito', models.BooleanField()),
                ('finalizado', models.BooleanField()),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratante', to='usuarios.usuario')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestador', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64, verbose_name='Título')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
                ('tags', models.CharField(max_length=640)),
                ('cidade', models.CharField(max_length=64)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='usuarios.usuario')),
            ],
        ),
    ]
