# Generated by Django 5.2.4 on 2025-07-07 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=64, unique=True)),
                ('documento', models.CharField(max_length=64, unique=True)),
                ('endereco', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64, verbose_name='Título')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
                ('tags', models.CharField(max_length=640)),
                ('cidade', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('cadastro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.cadastro')),
                ('cargo', models.CharField(max_length=64)),
            ],
            bases=('usuarios.cadastro',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cadastro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.cadastro')),
                ('data_nascimento', models.DateField()),
                ('is_banned', models.BooleanField(default=False)),
            ],
            bases=('usuarios.cadastro',),
        ),
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.IntegerField(verbose_name='Preço')),
                ('prazo', models.DateField()),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
                ('aceito', models.BooleanField()),
                ('finalizado', models.BooleanField()),
                ('anuncio_origem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anuncios', to='usuarios.anuncio')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratante', to='usuarios.usuario')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prestador', to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='usuarios.usuario'),
        ),
    ]
