# Generated by Django 5.2.4 on 2025-07-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacao',
            name='anuncio_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anuncios', to='usuarios.anuncio'),
        ),
        migrations.AlterField(
            model_name='contratacao',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratante', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='contratacao',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prestador', to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('insituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('data', models.DateField()),
                ('link', models.CharField(max_length=1000)),
                ('pendente', models.BooleanField()),
                ('aprovado', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuarios.usuario')),
            ],
        ),
    ]
