# Generated by Django 5.2.4 on 2025-07-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendente',
            name='anuncio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='usuarios.anuncio'),
            preserve_default=False,
        ),
    ]
