# Generated by Django 5.2.4 on 2025-07-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_contratacao_anuncio_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacao',
            name='anuncio_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anuncios', to='usuarios.anuncio'),
        ),
    ]
