# Generated by Django 5.2.4 on 2025-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_pendente_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacao',
            name='pendente',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='contratacao',
            name='aceito',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pendente',
        ),
    ]
