# Generated by Django 5.2.4 on 2025-07-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_contratacao_pendente_alter_contratacao_aceito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='insituicao',
            new_name='instituicao',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adm',
            name='nome',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='AnuncioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descricao', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=640)),
                ('cidade', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='usuarios.anuncio')),
            ],
        ),
    ]
